### ISSUE TITLE
Allow installing needs using install.packages :)

### ISSUE THREAD

**Issue by gka** [joshkatz/needs#1]
Or even better:

``` R
needs(needs)
```

**Comment by joshkatz** [comment]
That may take some doing... Though I like the idea! Convinced me to turn it into a package, so now you can do:

```
devtools::install_github("joshkatz/needs")
```

and, after the first time it loads, you never have to load it again. And there's no futzing about with user profiles (which is, generally speaking, a less than great thing to do).

For `install.packages(needs)` to be a thing, it'll have to make it past the [CRAN overlords](https://cran.r-project.org/web/packages/policies.html#Submission), which apparently is no small task.

**Comment by gka** [comment]
```
devtools::install_github("joshkatz/needs")
```

is perfect! thanks
